### ISSUE TITLE
Issue w merging Probabilities 

### ISSUE THREAD

**Issue by ratacad1** [RatAcad/dj_ratacad#28]
Traceback (most recent call last):
  File "/home/ratacad1/anaconda3/bin/dj-ratacad", line 8, in <module>
    sys.exit(cli())
  File "/home/ratacad1/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ratacad1/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ratacad1/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ratacad1/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ratacad1/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ratacad1/anaconda3/lib/python3.8/site-packages/dj_ratacad/cli.py", line 52, in update
    bpod.BpodTrialData.populate()
  File "/home/ratacad1/anaconda3/lib/python3.8/site-packages/dj_ratacad/bpod.py", line 461, in populate
    self._make_tuples(k)
  File "/home/ratacad1/anaconda3/lib/python3.8/site-packages/dj_ratacad/bpod.py", line 422, in _make_tuples
    bpod_data["TrialSettings"][ts][t]
TypeError: 'int' object is not subscriptable

**Comment by ratacad1** [comment]
@Crisds24 data from other tasks aren't being populated due to this error
